### ISSUE TITLE
Problem with playing with friends

### ISSUE THREAD

**Issue by Bobowonnell** [mouchoiresale/UltraMerge-agario-server#1]
So the server works fine but I have a problem with the IP address. It might be because I know nothing about doing this. Anyways whenever I get my IP address and add the port on my brothers phone to the blobio IP address box it doesn't work. Whenever you have the time can I get a more detailed tutorial on this. Also I am running this on chromebook terminal. Is it because I'm not running the server on android?

**Comment by kukikukiku** [comment]
it's old wait I upload a new server

**Comment by Bobowonnell** [comment]
Ok Thanks

**Comment by kukikukiku** [comment]
this server is designed to start on a computer, to run on blobio, you need either a terminal or you write: "cd src" "node index.js" or that you use a windows computer to launch the console then put your ip on blobio. 
I could give you more details on discord: mouchoire#4797

**Comment by Bobowonnell** [comment]
ok I will dm Im BOP BOP on dis

**Comment by mouchoiresale** [comment]
resolved
